title: Digital Asset Rights Standard (DARS)
description: The blockchain-based certification and licensing framework for all digital assets.
theme: jekyll-theme-cayman
show_downloads: false
github:
  is_project_page: true
  repository_url: https://github.com/JayMeeks75/digital-asset-rights-standard
